services:
  sbug_postgres:
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    container_name: spbug_postgres
    volumes:
      - ./data:/var/lib/postgresql/data